// Auto-extracted ECP method name constants from service adapters and server routing table.
// Source: /Users/keith/Development/ultra/src/ecp/server.ts + /Users/keith/Development/ultra/src/services/*/adapter.ts

// ---------------------------------------------------------------------------
// Utility type – produces the union of every leaf string value in a nested
// const object.
// ---------------------------------------------------------------------------
type DeepValues<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? { [K in keyof T]: DeepValues<T[K]> }[keyof T]
    : never;

// ---------------------------------------------------------------------------
// Methods const – every ECP method grouped by top-level namespace.
// Naming rule: strip the namespace prefix, then PascalCase the remainder.
//   document/open        → Open
//   ai/session/create    → SessionCreate
//   chat/todo/update-status → TodoUpdateStatus
// ---------------------------------------------------------------------------
export const Methods = {
  // ── Document ────────────────────────────────────────────────────────────
  Document: {
    Open: 'document/open',
    Close: 'document/close',
    Info: 'document/info',
    List: 'document/list',
    Content: 'document/content',
    Line: 'document/line',
    Lines: 'document/lines',
    TextInRange: 'document/textInRange',
    Version: 'document/version',
    Insert: 'document/insert',
    Delete: 'document/delete',
    Replace: 'document/replace',
    SetContent: 'document/setContent',
    Cursors: 'document/cursors',
    SetCursors: 'document/setCursors',
    SetCursor: 'document/setCursor',
    AddCursor: 'document/addCursor',
    MoveCursors: 'document/moveCursors',
    SelectAll: 'document/selectAll',
    ClearSelections: 'document/clearSelections',
    Selections: 'document/selections',
    Undo: 'document/undo',
    Redo: 'document/redo',
    CanUndo: 'document/canUndo',
    CanRedo: 'document/canRedo',
    IsDirty: 'document/isDirty',
    MarkClean: 'document/markClean',
    PositionToOffset: 'document/positionToOffset',
    OffsetToPosition: 'document/offsetToPosition',
    WordAtPosition: 'document/wordAtPosition',
  },

  // ── File ────────────────────────────────────────────────────────────────
  File: {
    Read: 'file/read',
    Write: 'file/write',
    Stat: 'file/stat',
    Exists: 'file/exists',
    Delete: 'file/delete',
    Rename: 'file/rename',
    Copy: 'file/copy',
    ReadDir: 'file/readDir',
    List: 'file/list',
    CreateDir: 'file/createDir',
    DeleteDir: 'file/deleteDir',
    BrowseDir: 'file/browseDir',
    Search: 'file/search',
    Glob: 'file/glob',
    Grep: 'file/grep',
    Edit: 'file/edit',
    Watch: 'file/watch',
    Unwatch: 'file/unwatch',
    PathToUri: 'file/pathToUri',
    UriToPath: 'file/uriToPath',
    GetParent: 'file/getParent',
    GetBasename: 'file/getBasename',
    Join: 'file/join',
  },

  // ── Git ─────────────────────────────────────────────────────────────────
  Git: {
    IsRepo: 'git/isRepo',
    GetRoot: 'git/getRoot',
    Status: 'git/status',
    Branch: 'git/branch',
    Stage: 'git/stage',
    StageAll: 'git/stageAll',
    Unstage: 'git/unstage',
    Discard: 'git/discard',
    Diff: 'git/diff',
    DiffLines: 'git/diffLines',
    DiffBuffer: 'git/diffBuffer',
    Commit: 'git/commit',
    Amend: 'git/amend',
    Log: 'git/log',
    FileLog: 'git/fileLog',
    Branches: 'git/branches',
    CreateBranch: 'git/createBranch',
    SwitchBranch: 'git/switchBranch',
    DeleteBranch: 'git/deleteBranch',
    RenameBranch: 'git/renameBranch',
    Push: 'git/push',
    Pull: 'git/pull',
    Fetch: 'git/fetch',
    Remotes: 'git/remotes',
    SetUpstream: 'git/setUpstream',
    Merge: 'git/merge',
    MergeAbort: 'git/mergeAbort',
    Conflicts: 'git/conflicts',
    IsMerging: 'git/isMerging',
    Stash: 'git/stash',
    StashPop: 'git/stashPop',
    StashList: 'git/stashList',
    StashDrop: 'git/stashDrop',
    StashApply: 'git/stashApply',
    Blame: 'git/blame',
    Show: 'git/show',
  },

  // ── Config ──────────────────────────────────────────────────────────────
  Config: {
    Get: 'config/get',
    Set: 'config/set',
    GetAll: 'config/getAll',
    Reset: 'config/reset',
    Schema: 'config/schema',
  },

  // ── Session ─────────────────────────────────────────────────────────────
  Session: {
    Save: 'session/save',
    Load: 'session/load',
    List: 'session/list',
    Delete: 'session/delete',
    Current: 'session/current',
    SetCurrent: 'session/setCurrent',
    MarkDirty: 'session/markDirty',
    LoadLast: 'session/loadLast',
  },

  // ── Keybindings ─────────────────────────────────────────────────────────
  Keybindings: {
    Get: 'keybindings/get',
    Set: 'keybindings/set',
    Add: 'keybindings/add',
    Remove: 'keybindings/remove',
    Resolve: 'keybindings/resolve',
  },

  // ── Commands ────────────────────────────────────────────────────────────
  Commands: {
    List: 'commands/list',
  },

  // ── Theme ───────────────────────────────────────────────────────────────
  Theme: {
    List: 'theme/list',
    Get: 'theme/get',
    Set: 'theme/set',
    Current: 'theme/current',
  },

  // ── Workspace ───────────────────────────────────────────────────────────
  Workspace: {
    GetRoot: 'workspace/getRoot',
    SetRoot: 'workspace/setRoot',
  },

  // ── SystemPrompt ────────────────────────────────────────────────────────
  SystemPrompt: {
    Get: 'systemPrompt/get',
    Set: 'systemPrompt/set',
  },

  // ── Terminal ────────────────────────────────────────────────────────────
  Terminal: {
    Create: 'terminal/create',
    AttachTmux: 'terminal/attachTmux',
    Close: 'terminal/close',
    CloseAll: 'terminal/closeAll',
    Write: 'terminal/write',
    Resize: 'terminal/resize',
    GetBuffer: 'terminal/getBuffer',
    Scroll: 'terminal/scroll',
    ScrollToBottom: 'terminal/scrollToBottom',
    GetInfo: 'terminal/getInfo',
    List: 'terminal/list',
    Exists: 'terminal/exists',
    IsRunning: 'terminal/isRunning',
    Execute: 'terminal/execute',
    Spawn: 'terminal/spawn',
  },

  // ── LSP ─────────────────────────────────────────────────────────────────
  Lsp: {
    Start: 'lsp/start',
    Stop: 'lsp/stop',
    Status: 'lsp/status',
    DocumentOpen: 'lsp/documentOpen',
    DocumentChange: 'lsp/documentChange',
    DocumentSave: 'lsp/documentSave',
    DocumentClose: 'lsp/documentClose',
    Completion: 'lsp/completion',
    Hover: 'lsp/hover',
    SignatureHelp: 'lsp/signatureHelp',
    Definition: 'lsp/definition',
    References: 'lsp/references',
    DocumentSymbol: 'lsp/documentSymbol',
    Rename: 'lsp/rename',
    Diagnostics: 'lsp/diagnostics',
    AllDiagnostics: 'lsp/allDiagnostics',
    DiagnosticsSummary: 'lsp/diagnosticsSummary',
    SetServerConfig: 'lsp/setServerConfig',
    GetServerConfig: 'lsp/getServerConfig',
    GetLanguageId: 'lsp/getLanguageId',
    HasServerFor: 'lsp/hasServerFor',
  },

  // ── Syntax ──────────────────────────────────────────────────────────────
  Syntax: {
    Highlight: 'syntax/highlight',
    HighlightLine: 'syntax/highlightLine',
    CreateSession: 'syntax/createSession',
    UpdateSession: 'syntax/updateSession',
    GetSessionTokens: 'syntax/getSessionTokens',
    GetSessionAllTokens: 'syntax/getSessionAllTokens',
    DisposeSession: 'syntax/disposeSession',
    GetSession: 'syntax/getSession',
    Languages: 'syntax/languages',
    IsSupported: 'syntax/isSupported',
    DetectLanguage: 'syntax/detectLanguage',
    Themes: 'syntax/themes',
    SetTheme: 'syntax/setTheme',
    GetTheme: 'syntax/getTheme',
    Metrics: 'syntax/metrics',
    ResetMetrics: 'syntax/resetMetrics',
    IsReady: 'syntax/isReady',
    WaitForReady: 'syntax/waitForReady',
  },

  // ── Secret ──────────────────────────────────────────────────────────────
  Secret: {
    Get: 'secret/get',
    Set: 'secret/set',
    Delete: 'secret/delete',
    List: 'secret/list',
    Has: 'secret/has',
    Info: 'secret/info',
    Providers: 'secret/providers',
  },

  // ── Database ────────────────────────────────────────────────────────────
  Database: {
    CreateConnection: 'database/createConnection',
    Connect: 'database/connect',
    Disconnect: 'database/disconnect',
    DeleteConnection: 'database/deleteConnection',
    ListConnections: 'database/listConnections',
    GetConnection: 'database/getConnection',
    TestConnection: 'database/testConnection',
    UpdateConnection: 'database/updateConnection',
    Query: 'database/query',
    Transaction: 'database/transaction',
    Cancel: 'database/cancel',
    FetchRows: 'database/fetchRows',
    ListSchemas: 'database/listSchemas',
    ListTables: 'database/listTables',
    DescribeTable: 'database/describeTable',
    GetTableDDL: 'database/getTableDDL',
    History: 'database/history',
    SearchHistory: 'database/searchHistory',
    ClearHistory: 'database/clearHistory',
    FavoriteQuery: 'database/favoriteQuery',
    GetFavorites: 'database/getFavorites',
  },

  // ── AI ──────────────────────────────────────────────────────────────────
  Ai: {
    Providers: 'ai/providers',
    ProviderCapabilities: 'ai/provider/capabilities',
    ProviderAvailable: 'ai/provider/available',
    ProviderModels: 'ai/provider/models',
    SessionCreate: 'ai/session/create',
    SessionGet: 'ai/session/get',
    SessionList: 'ai/session/list',
    SessionDelete: 'ai/session/delete',
    SessionClear: 'ai/session/clear',
    MessageSend: 'ai/message/send',
    MessageStream: 'ai/message/stream',
    MessageCancel: 'ai/message/cancel',
    MessageAdd: 'ai/message/add',
    Messages: 'ai/messages',
    Tools: 'ai/tools',
    ToolsEcp: 'ai/tools/ecp',
    ToolExecute: 'ai/tool/execute',
    PermissionApprove: 'ai/permission/approve',
    PermissionDeny: 'ai/permission/deny',
    Permissions: 'ai/permissions',
    PermissionsAutoApproved: 'ai/permissions/auto-approved',
    PermissionsSession: 'ai/permissions/session',
    PermissionsFolder: 'ai/permissions/folder',
    PermissionsGlobal: 'ai/permissions/global',
    PermissionsSessionClear: 'ai/permissions/session/clear',
    PermissionRemove: 'ai/permission/remove',
    MiddlewareList: 'ai/middleware/list',
    MiddlewareEnable: 'ai/middleware/enable',
    PipelineConfig: 'ai/pipeline/config',
    TodoWrite: 'ai/todo/write',
    TodoGet: 'ai/todo/get',
    AgentList: 'ai/agent/list',
    AgentGet: 'ai/agent/get',
    AgentStatus: 'ai/agent/status',
    AgentUpdate: 'ai/agent/update',
    AgentConfigReload: 'ai/agent/config/reload',
    SessionAgents: 'ai/session/agents',
    SessionAgentAdd: 'ai/session/agent/add',
    SessionAgentRemove: 'ai/session/agent/remove',
    MentionSuggest: 'ai/mention/suggest',
    PersonaList: 'ai/persona/list',
    PersonaGet: 'ai/persona/get',
    PersonaCreate: 'ai/persona/create',
    PersonaUpdate: 'ai/persona/update',
    PersonaDelete: 'ai/persona/delete',
    PersonaCompress: 'ai/persona/compress',
  },

  // ── Chat ────────────────────────────────────────────────────────────────
  Chat: {
    SessionCreate: 'chat/session/create',
    SessionGet: 'chat/session/get',
    SessionUpdate: 'chat/session/update',
    SessionDelete: 'chat/session/delete',
    SessionList: 'chat/session/list',
    MessageAdd: 'chat/message/add',
    MessageUpdate: 'chat/message/update',
    MessageDelete: 'chat/message/delete',
    MessageList: 'chat/message/list',
    MessageSearch: 'chat/message/search',
    MessageRecent: 'chat/message/recent',
    ToolCallAdd: 'chat/toolCall/add',
    ToolCallComplete: 'chat/toolCall/complete',
    ToolCallUpdateInput: 'chat/toolCall/updateInput',
    ToolCallList: 'chat/toolCall/list',
    PermissionCheck: 'chat/permission/check',
    PermissionGrant: 'chat/permission/grant',
    PermissionRevoke: 'chat/permission/revoke',
    PermissionList: 'chat/permission/list',
    ActivityLog: 'chat/activity/log',
    ActivitySince: 'chat/activity/since',
    ActivityAdd: 'chat/activity/add',
    CompactionCreate: 'chat/compaction/create',
    CompactionGet: 'chat/compaction/get',
    CompactionList: 'chat/compaction/list',
    CompactionExpand: 'chat/compaction/expand',
    CompactionCollapse: 'chat/compaction/collapse',
    CompactionDelete: 'chat/compaction/delete',
    ContextBuild: 'chat/context/build',
    TodoUpsert: 'chat/todo/upsert',
    TodoGet: 'chat/todo/get',
    TodoList: 'chat/todo/list',
    TodoUpdateStatus: 'chat/todo/update-status',
    TodoDelete: 'chat/todo/delete',
    TodoReplace: 'chat/todo/replace',
    DocumentCreate: 'chat/document/create',
    DocumentGet: 'chat/document/get',
    DocumentList: 'chat/document/list',
    DocumentUpdate: 'chat/document/update',
    DocumentDelete: 'chat/document/delete',
    DocumentSearch: 'chat/document/search',
    DocumentHierarchy: 'chat/document/hierarchy',
    DocumentVulnerabilities: 'chat/document/vulnerabilities',
    DocumentPendingReviews: 'chat/document/pending-reviews',
    DocumentCountByType: 'chat/document/count-by-type',
    PlanCreate: 'chat/plan/create',
    PlanGet: 'chat/plan/get',
    PlanList: 'chat/plan/list',
    PlanUpdate: 'chat/plan/update',
    PlanDelete: 'chat/plan/delete',
    PlanContent: 'chat/plan/content',
    SpecCreate: 'chat/spec/create',
    SpecGet: 'chat/spec/get',
    SpecList: 'chat/spec/list',
    SpecUpdate: 'chat/spec/update',
    SpecDelete: 'chat/spec/delete',
    SpecHierarchy: 'chat/spec/hierarchy',
    SpecLinkPlan: 'chat/spec/link-plan',
    Stats: 'chat/stats',
  },

  // ── Workflow ────────────────────────────────────────────────────────────
  Workflow: {
    List: 'workflow/list',
    Get: 'workflow/get',
    Create: 'workflow/create',
    Update: 'workflow/update',
    Delete: 'workflow/delete',
    SetDefault: 'workflow/setDefault',
    Convert: 'workflow/convert',
    Validate: 'workflow/validate',
    ConvertToEditor: 'workflow/convertToEditor',
    ExecuteStart: 'workflow/execute/start',
    ExecuteStep: 'workflow/execute/step',
    ExecutePause: 'workflow/execute/pause',
    ExecuteResume: 'workflow/execute/resume',
    ExecuteCancel: 'workflow/execute/cancel',
    ExecuteGet: 'workflow/execute/get',
    ExecuteList: 'workflow/execute/list',
    ContextList: 'workflow/context/list',
    ContextAdd: 'workflow/context/add',
    ContextCompact: 'workflow/context/compact',
    ContextExpand: 'workflow/context/expand',
    ContextBudget: 'workflow/context/budget',
    CheckpointRespond: 'workflow/checkpoint/respond',
    CheckpointGet: 'workflow/checkpoint/get',
    CheckpointList: 'workflow/checkpoint/list',
    FeedbackList: 'workflow/feedback/list',
    FeedbackAddress: 'workflow/feedback/address',
    FeedbackDismiss: 'workflow/feedback/dismiss',
    PermissionCheck: 'workflow/permission/check',
    PermissionGrant: 'workflow/permission/grant',
    PermissionDeny: 'workflow/permission/deny',
    MessageList: 'workflow/message/list',
    MessageSend: 'workflow/message/send',
    MessageGet: 'workflow/message/get',
    AgentList: 'workflow/agent/list',
    AgentGet: 'workflow/agent/get',
    AgentCreate: 'workflow/agent/create',
    AgentUpdate: 'workflow/agent/update',
    AgentDelete: 'workflow/agent/delete',
    AgentDuplicate: 'workflow/agent/duplicate',
    ExecutionTools: 'workflow/execution/tools',
    ExecutionToolsGrouped: 'workflow/execution/tools/grouped',
    ToolCallGet: 'workflow/toolCall/get',
    ToolCallCreate: 'workflow/toolCall/create',
    ToolCallApprove: 'workflow/toolCall/approve',
    ToolCallDeny: 'workflow/toolCall/deny',
    ActivityLog: 'workflow/activity/log',
    ReviewPanelDecide: 'workflow/review_panel/decide',
    DebugInfo: 'workflow/debug/info',
  },

  // ── Agent ───────────────────────────────────────────────────────────────
  Agent: {
    RoleList: 'agent/role/list',
    RoleGet: 'agent/role/get',
    Create: 'agent/create',
    Get: 'agent/get',
    List: 'agent/list',
    Delete: 'agent/delete',
    Invoke: 'agent/invoke',
    StateGet: 'agent/state/get',
    StateSave: 'agent/state/save',
    MessageSend: 'agent/message/send',
    MessageList: 'agent/message/list',
    MessageAcknowledge: 'agent/message/acknowledge',
    MemoryGet: 'agent/memory/get',
    MemorySet: 'agent/memory/set',
    MemoryDelete: 'agent/memory/delete',
    MemoryKeys: 'agent/memory/keys',
  },

  // ── Auth ────────────────────────────────────────────────────────────────
  Auth: {
    Providers: 'auth/providers',
    Status: 'auth/status',
    OauthStart: 'auth/oauth/start',
    OauthCallback: 'auth/oauth/callback',
    ApikeySet: 'auth/apikey/set',
    ApikeyGet: 'auth/apikey/get',
    ApikeyDelete: 'auth/apikey/delete',
    Switch: 'auth/switch',
    OauthClear: 'auth/oauth/clear',
    ApikeyClear: 'auth/apikey/clear',
    Logout: 'auth/logout',
  },

  // ── Models (server.ts inline) ──────────────────────────────────────────
  Models: {
    List: 'models/list',
    Refresh: 'models/refresh',
  },

  // ── Shell (server.ts inline) ───────────────────────────────────────────
  Shell: {
    Reveal: 'shell/reveal',
    OpenExternal: 'shell/openExternal',
    Rebuild: 'shell/rebuild',
  },

  // ── Layout (server.ts inline) ──────────────────────────────────────────
  Layout: {
    AddTab: 'layout/addTab',
    SplitTile: 'layout/splitTile',
    FocusTile: 'layout/focusTile',
    OpenFile: 'layout/openFile',
    SetPreset: 'layout/setPreset',
    CloseTile: 'layout/closeTile',
    GetLayout: 'layout/getLayout',
    ReportState: 'layout/reportState',
    CloseTab: 'layout/closeTab',
    ActivateTab: 'layout/activateTab',
  },
} as const;

// ---------------------------------------------------------------------------
// MethodName – union of every method string in the protocol.
// ---------------------------------------------------------------------------
export type MethodName = DeepValues<typeof Methods>;
