/**
 * Default Configuration (Auto-generated)
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit the JSONC files in config/ and run build to regenerate.
 *
 * Generated from:
 *   - config/default-keybindings.jsonc
 *   - config/default-settings.jsonc
 *   - config/default-commands.jsonc
 *   - config/themes/*.json
 *   - config/BOOT.md
 */

import type { KeyBinding, Theme, CommandInfo } from '../services/session/types.ts';

export const defaultKeybindings: KeyBinding[] = [
  {
    "key": "ctrl+s",
    "command": "file.save"
  },
  {
    "key": "meta+s",
    "command": "file.save"
  },
  {
    "key": "ctrl+shift+s",
    "command": "file.saveAs"
  },
  {
    "key": "shift+meta+s",
    "command": "file.saveAs"
  },
  {
    "key": "ctrl+o",
    "command": "file.open"
  },
  {
    "key": "meta+o",
    "command": "file.open"
  },
  {
    "key": "ctrl+n",
    "command": "file.new"
  },
  {
    "key": "meta+n",
    "command": "file.new"
  },
  {
    "key": "ctrl+w",
    "command": "file.close"
  },
  {
    "key": "meta+w",
    "command": "file.close"
  },
  {
    "key": "ctrl+tab",
    "command": "file.nextTab"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "file.previousTab"
  },
  {
    "key": "meta+alt+right",
    "command": "file.nextTab"
  },
  {
    "key": "meta+alt+left",
    "command": "file.previousTab"
  },
  {
    "key": "ctrl+z",
    "command": "edit.undo"
  },
  {
    "key": "meta+z",
    "command": "edit.undo"
  },
  {
    "key": "ctrl+shift+z",
    "command": "edit.redo"
  },
  {
    "key": "shift+meta+z",
    "command": "edit.redo"
  },
  {
    "key": "ctrl+y",
    "command": "edit.redo"
  },
  {
    "key": "ctrl+c",
    "command": "edit.copy"
  },
  {
    "key": "meta+c",
    "command": "edit.copy"
  },
  {
    "key": "ctrl+x",
    "command": "edit.cut"
  },
  {
    "key": "meta+x",
    "command": "edit.cut"
  },
  {
    "key": "ctrl+v",
    "command": "edit.paste"
  },
  {
    "key": "meta+v",
    "command": "edit.paste"
  },
  {
    "key": "ctrl+a",
    "command": "edit.selectAll"
  },
  {
    "key": "meta+a",
    "command": "edit.selectAll"
  },
  {
    "key": "ctrl+d",
    "command": "edit.selectNextMatch"
  },
  {
    "key": "meta+d",
    "command": "edit.selectNextMatch"
  },
  {
    "key": "ctrl+shift+l",
    "command": "edit.selectAllOccurrences"
  },
  {
    "key": "meta+d a",
    "command": "edit.selectAllOccurrences"
  },
  {
    "key": "ctrl+alt+up",
    "command": "editor.addCursorAbove"
  },
  {
    "key": "ctrl+alt+down",
    "command": "editor.addCursorBelow"
  },
  {
    "key": "escape",
    "command": "editor.clearCursors",
    "when": "editorHasMultipleCursors"
  },
  {
    "key": "ctrl+f",
    "command": "search.find"
  },
  {
    "key": "meta+f",
    "command": "search.find"
  },
  {
    "key": "ctrl+h",
    "command": "search.replace"
  },
  {
    "key": "meta+h",
    "command": "search.replace"
  },
  {
    "key": "ctrl+shift+f",
    "command": "search.findInFiles"
  },
  {
    "key": "shift+meta+f",
    "command": "search.findInFiles"
  },
  {
    "key": "f3",
    "command": "search.findNext"
  },
  {
    "key": "shift+f3",
    "command": "search.findPrevious"
  },
  {
    "key": "ctrl+g",
    "command": "editor.gotoLine"
  },
  {
    "key": "ctrl+p",
    "command": "workbench.quickOpen"
  },
  {
    "key": "meta+p",
    "command": "workbench.quickOpen"
  },
  {
    "key": "ctrl+shift+p",
    "command": "workbench.commandPalette"
  },
  {
    "key": "shift+meta+p",
    "command": "workbench.commandPalette"
  },
  {
    "key": "ctrl+r",
    "command": "editor.gotoSymbol"
  },
  {
    "key": "meta+r",
    "command": "editor.gotoSymbol"
  },
  {
    "key": "ctrl+shift+r",
    "command": "editor.gotoWorkspaceSymbol"
  },
  {
    "key": "shift+meta+r",
    "command": "editor.gotoWorkspaceSymbol"
  },
  {
    "key": "ctrl+shift+a",
    "command": "pane.addPanel"
  },
  {
    "key": "shift+meta+a",
    "command": "pane.addPanel"
  },
  {
    "key": "ctrl+]",
    "command": "workbench.focusNextPane"
  },
  {
    "key": "meta+]",
    "command": "workbench.focusNextPane"
  },
  {
    "key": "ctrl+[",
    "command": "workbench.focusPreviousPane"
  },
  {
    "key": "meta+[",
    "command": "workbench.focusPreviousPane"
  },
  {
    "key": "ctrl+shift+b",
    "command": "workbench.toggleSidebar"
  },
  {
    "key": "ctrl+`",
    "command": "workbench.toggleTerminal"
  },
  {
    "key": "ctrl+\\",
    "command": "view.splitVertical"
  },
  {
    "key": "meta+\\",
    "command": "view.splitVertical"
  },
  {
    "key": "ctrl+shift+\\",
    "command": "view.splitHorizontal"
  },
  {
    "key": "shift+meta+\\",
    "command": "view.splitHorizontal"
  },
  {
    "key": "ctrl+1",
    "command": "workbench.focusEditor1"
  },
  {
    "key": "ctrl+2",
    "command": "workbench.focusEditor2"
  },
  {
    "key": "ctrl+3",
    "command": "workbench.focusEditor3"
  },
  {
    "key": "ctrl+l",
    "command": "editor.selectLine"
  },
  {
    "key": "meta+l",
    "command": "editor.selectLine"
  },
  {
    "key": "ctrl+l d",
    "command": "editor.duplicateLine"
  },
  {
    "key": "ctrl+shift+d",
    "command": "editor.duplicateSelection"
  },
  {
    "key": "ctrl+shift+`",
    "command": "terminal.new"
  },
  {
    "key": "ctrl+shift+t",
    "command": "terminal.newInPane"
  },
  {
    "key": "ctrl+shift+g",
    "command": "git.focusPanel"
  },
  {
    "key": "ctrl+shift+i",
    "command": "ai.toggleChat"
  },
  {
    "key": "shift+meta+i",
    "command": "ai.toggleChat"
  },
  {
    "key": "ctrl+alt+i",
    "command": "ai.toggleServiceChat"
  },
  {
    "key": "alt+meta+i",
    "command": "ai.toggleServiceChat"
  },
  {
    "key": "ctrl+shift+p",
    "command": "ai.showPermissions",
    "when": "aiChatFocus"
  },
  {
    "key": "shift+meta+p",
    "command": "ai.showPermissions",
    "when": "aiChatFocus"
  },
  {
    "key": "s",
    "command": "gitPanel.stage",
    "when": "gitPanelFocus"
  },
  {
    "key": "shift+s",
    "command": "gitPanel.stageAll",
    "when": "gitPanelFocus"
  },
  {
    "key": "u",
    "command": "gitPanel.unstage",
    "when": "gitPanelFocus"
  },
  {
    "key": "d",
    "command": "gitPanel.discard",
    "when": "gitPanelFocus"
  },
  {
    "key": "Enter",
    "command": "gitPanel.openDiff",
    "when": "gitPanelFocus"
  },
  {
    "key": "o",
    "command": "gitPanel.openFile",
    "when": "gitPanelFocus"
  },
  {
    "key": "r",
    "command": "gitPanel.refresh",
    "when": "gitPanelFocus"
  },
  {
    "key": "c",
    "command": "gitPanel.commit",
    "when": "gitPanelFocus"
  },
  {
    "key": " ",
    "command": "gitPanel.toggleSection",
    "when": "gitPanelFocus"
  },
  {
    "key": "ArrowUp",
    "command": "gitPanel.moveUp",
    "when": "gitPanelFocus"
  },
  {
    "key": "ArrowDown",
    "command": "gitPanel.moveDown",
    "when": "gitPanelFocus"
  },
  {
    "key": "k",
    "command": "gitPanel.moveUp",
    "when": "gitPanelFocus"
  },
  {
    "key": "j",
    "command": "gitPanel.moveDown",
    "when": "gitPanelFocus"
  },
  {
    "key": "ArrowUp",
    "command": "fileTree.moveUp",
    "when": "fileTreeFocus"
  },
  {
    "key": "ArrowDown",
    "command": "fileTree.moveDown",
    "when": "fileTreeFocus"
  },
  {
    "key": "ArrowRight",
    "command": "fileTree.expand",
    "when": "fileTreeFocus"
  },
  {
    "key": "ArrowLeft",
    "command": "fileTree.collapse",
    "when": "fileTreeFocus"
  },
  {
    "key": "Enter",
    "command": "fileTree.open",
    "when": "fileTreeFocus"
  },
  {
    "key": " ",
    "command": "fileTree.open",
    "when": "fileTreeFocus"
  },
  {
    "key": "n",
    "command": "fileTree.newFile",
    "when": "fileTreeFocus"
  },
  {
    "key": "shift+n",
    "command": "fileTree.newFolder",
    "when": "fileTreeFocus"
  },
  {
    "key": "r",
    "command": "fileTree.rename",
    "when": "fileTreeFocus"
  },
  {
    "key": "F2",
    "command": "fileTree.rename",
    "when": "fileTreeFocus"
  },
  {
    "key": "d",
    "command": "fileTree.delete",
    "when": "fileTreeFocus"
  },
  {
    "key": "Delete",
    "command": "fileTree.delete",
    "when": "fileTreeFocus"
  },
  {
    "key": "k",
    "command": "fileTree.moveUp",
    "when": "fileTreeFocus"
  },
  {
    "key": "j",
    "command": "fileTree.moveDown",
    "when": "fileTreeFocus"
  },
  {
    "key": "l",
    "command": "fileTree.expand",
    "when": "fileTreeFocus"
  },
  {
    "key": "h",
    "command": "fileTree.collapse",
    "when": "fileTreeFocus"
  },
  {
    "key": "Home",
    "command": "fileTree.goToFirst",
    "when": "fileTreeFocus"
  },
  {
    "key": "End",
    "command": "fileTree.goToLast",
    "when": "fileTreeFocus"
  },
  {
    "key": "PageUp",
    "command": "fileTree.pageUp",
    "when": "fileTreeFocus"
  },
  {
    "key": "PageDown",
    "command": "fileTree.pageDown",
    "when": "fileTreeFocus"
  },
  {
    "key": "ArrowUp",
    "command": "outlinePanel.moveUp",
    "when": "outlinePanelFocus"
  },
  {
    "key": "ArrowDown",
    "command": "outlinePanel.moveDown",
    "when": "outlinePanelFocus"
  },
  {
    "key": "ArrowRight",
    "command": "outlinePanel.expand",
    "when": "outlinePanelFocus"
  },
  {
    "key": "ArrowLeft",
    "command": "outlinePanel.collapse",
    "when": "outlinePanelFocus"
  },
  {
    "key": " ",
    "command": "outlinePanel.toggleExpand",
    "when": "outlinePanelFocus"
  },
  {
    "key": "Enter",
    "command": "outlinePanel.select",
    "when": "outlinePanelFocus"
  },
  {
    "key": "PageUp",
    "command": "outlinePanel.pageUp",
    "when": "outlinePanelFocus"
  },
  {
    "key": "PageDown",
    "command": "outlinePanel.pageDown",
    "when": "outlinePanelFocus"
  },
  {
    "key": "Home",
    "command": "outlinePanel.goToFirst",
    "when": "outlinePanelFocus"
  },
  {
    "key": "End",
    "command": "outlinePanel.goToLast",
    "when": "outlinePanelFocus"
  },
  {
    "key": "k",
    "command": "outlinePanel.moveUp",
    "when": "outlinePanelFocus"
  },
  {
    "key": "j",
    "command": "outlinePanel.moveDown",
    "when": "outlinePanelFocus"
  },
  {
    "key": "l",
    "command": "outlinePanel.expand",
    "when": "outlinePanelFocus"
  },
  {
    "key": "h",
    "command": "outlinePanel.collapse",
    "when": "outlinePanelFocus"
  },
  {
    "key": "ArrowUp",
    "command": "timelinePanel.moveUp",
    "when": "timelinePanelFocus"
  },
  {
    "key": "ArrowDown",
    "command": "timelinePanel.moveDown",
    "when": "timelinePanelFocus"
  },
  {
    "key": "PageUp",
    "command": "timelinePanel.pageUp",
    "when": "timelinePanelFocus"
  },
  {
    "key": "PageDown",
    "command": "timelinePanel.pageDown",
    "when": "timelinePanelFocus"
  },
  {
    "key": "Home",
    "command": "timelinePanel.goToFirst",
    "when": "timelinePanelFocus"
  },
  {
    "key": "End",
    "command": "timelinePanel.goToLast",
    "when": "timelinePanelFocus"
  },
  {
    "key": "g",
    "command": "timelinePanel.goToFirst",
    "when": "timelinePanelFocus"
  },
  {
    "key": "shift+g",
    "command": "timelinePanel.goToLast",
    "when": "timelinePanelFocus"
  },
  {
    "key": "Enter",
    "command": "timelinePanel.viewDiff",
    "when": "timelinePanelFocus"
  },
  {
    "key": "o",
    "command": "timelinePanel.openFileAtCommit",
    "when": "timelinePanelFocus"
  },
  {
    "key": "Tab",
    "command": "timelinePanel.toggleMode",
    "when": "timelinePanelFocus"
  },
  {
    "key": "k",
    "command": "timelinePanel.moveUp",
    "when": "timelinePanelFocus"
  },
  {
    "key": "j",
    "command": "timelinePanel.moveDown",
    "when": "timelinePanelFocus"
  },
  {
    "key": "y",
    "command": "timelinePanel.copyHash",
    "when": "timelinePanelFocus"
  },
  {
    "key": "ArrowUp",
    "command": "queryResults.moveUp",
    "when": "queryResultsFocus"
  },
  {
    "key": "ArrowDown",
    "command": "queryResults.moveDown",
    "when": "queryResultsFocus"
  },
  {
    "key": "ArrowLeft",
    "command": "queryResults.moveLeft",
    "when": "queryResultsFocus"
  },
  {
    "key": "ArrowRight",
    "command": "queryResults.moveRight",
    "when": "queryResultsFocus"
  },
  {
    "key": "PageUp",
    "command": "queryResults.pageUp",
    "when": "queryResultsFocus"
  },
  {
    "key": "PageDown",
    "command": "queryResults.pageDown",
    "when": "queryResultsFocus"
  },
  {
    "key": "Home",
    "command": "queryResults.goToFirst",
    "when": "queryResultsFocus"
  },
  {
    "key": "End",
    "command": "queryResults.goToLast",
    "when": "queryResultsFocus"
  },
  {
    "key": "Enter",
    "command": "queryResults.showDetails",
    "when": "queryResultsFocus"
  },
  {
    "key": "r",
    "command": "queryResults.refresh",
    "when": "queryResultsFocus"
  },
  {
    "key": "F5",
    "command": "queryResults.refresh",
    "when": "queryResultsFocus"
  },
  {
    "key": "e",
    "command": "queryResults.export",
    "when": "queryResultsFocus"
  },
  {
    "key": "s",
    "command": "queryResults.sort",
    "when": "queryResultsFocus"
  },
  {
    "key": "Tab",
    "command": "queryResults.toggleViewMode",
    "when": "queryResultsFocus"
  },
  {
    "key": "k",
    "command": "queryResults.moveUp",
    "when": "queryResultsFocus"
  },
  {
    "key": "j",
    "command": "queryResults.moveDown",
    "when": "queryResultsFocus"
  },
  {
    "key": "h",
    "command": "queryResults.moveLeft",
    "when": "queryResultsFocus"
  },
  {
    "key": "l",
    "command": "queryResults.moveRight",
    "when": "queryResultsFocus"
  },
  {
    "key": "ctrl+q",
    "command": "workbench.quit"
  },
  {
    "key": "meta+q",
    "command": "workbench.quit"
  },
  {
    "key": "ctrl+,",
    "command": "workbench.openSettings"
  },
  {
    "key": "meta+,",
    "command": "workbench.openSettings"
  },
  {
    "key": "ctrl+shift+,",
    "command": "workbench.openKeybindings"
  },
  {
    "key": "ctrl+k ctrl+s",
    "command": "session.saveAs"
  },
  {
    "key": "ctrl+k ctrl+o",
    "command": "session.open"
  },
  {
    "key": "ctrl+shift+[",
    "command": "editor.fold"
  },
  {
    "key": "ctrl+shift+]",
    "command": "editor.unfold"
  },
  {
    "key": "ctrl+k ctrl+0",
    "command": "editor.foldAll"
  },
  {
    "key": "ctrl+k ctrl+j",
    "command": "editor.unfoldAll"
  },
  {
    "key": "ctrl+k ctrl+c",
    "command": "editor.commentLine"
  },
  {
    "key": "ctrl+k ctrl+u",
    "command": "editor.uncommentLine"
  },
  {
    "key": "ctrl+/",
    "command": "editor.toggleComment"
  },
  {
    "key": "meta+/",
    "command": "editor.toggleComment"
  },
  {
    "key": "ctrl+shift+k",
    "command": "lsp.goToDefinition"
  },
  {
    "key": "ctrl+i",
    "command": "lsp.showHover"
  },
  {
    "key": "ctrl+space",
    "command": "lsp.triggerCompletion"
  },
  {
    "key": "ctrl+shift+space",
    "command": "lsp.triggerSignatureHelp"
  },
  {
    "key": "ctrl+shift+e",
    "command": "ensemble.toggle"
  },
  {
    "key": "shift+meta+e",
    "command": "ensemble.toggle"
  }
];

export const defaultSettings: Record<string, any> = {
  "editor.fontSize": 14,
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "editor.autoIndent": "full",
  "editor.autoClosingBrackets": "always",
  "editor.wordWrap": "on",
  "editor.lineNumbers": "on",
  "editor.folding": true,
  "editor.renderWhitespace": "selection",
  "editor.mouseWheelScrollSensitivity": 3,
  "editor.cursorBlinkRate": 500,
  "editor.scrollBeyondLastLine": true,
  "editor.diagnostics.curlyUnderline": true,
  "editor.undoHistoryLimit": 1000,
  "editor.minimap.enabled": true,
  "editor.minimap.width": 10,
  "editor.minimap.showSlider": "always",
  "editor.minimap.maxColumn": 120,
  "editor.minimap.side": "right",
  "files.autoSave": "off",
  "files.watchFiles": "onFocus",
  "files.exclude": {
    "**/node_modules": true,
    "**/.git": true,
    "**/.DS_Store": true
  },
  "workbench.colorTheme": "catppuccin-frappe",
  "workbench.startupEditor": "",
  "tui.sidebar.width": 36,
  "tui.sidebar.visible": true,
  "tui.sidebar.location": "left",
  "tui.sidebar.focusedBackground": "#2d3139",
  "tui.terminal.height": 24,
  "tui.terminal.scrollback": 1000,
  "tui.fileTree.showGitStatus": true,
  "tui.tabBar.scrollAmount": 1,
  "tui.filePicker.maxFiles": 10000,
  "tui.diffViewer.autoRefresh": true,
  "tui.diffViewer.showDiagnostics": true,
  "tui.diffViewer.editMode": "stage-modified",
  "tui.outline.collapsedOnStartup": true,
  "tui.outline.autoFollow": true,
  "tui.timeline.collapsedOnStartup": true,
  "tui.timeline.mode": "file",
  "tui.timeline.commitCount": 50,
  "git.statusInterval": 500,
  "git.panel.location": "sidebar-bottom",
  "git.panel.openOnStartup": true,
  "git.diffContextLines": 3,
  "git.inlineDiff.maxHeight": 15,
  "git.inlineDiff.contextLines": 3,
  "ai.defaultProvider": "claude-code",
  "ai.panel.defaultWidth": 80,
  "ai.panel.maxWidthPercent": 50,
  "ai.panel.openOnStartup": false,
  "ai.panel.initialPrompt": "You are a helpful software engineer working with another software engineer on a coding project using the Ultra IDE",
  "ensemble.asciiIcons": false,
  "session.restoreOnStartup": true,
  "session.autoSave": true,
  "session.autoSaveInterval": 30000,
  "session.save.openFiles": true,
  "session.save.cursorPositions": true,
  "session.save.scrollPositions": true,
  "session.save.foldState": true,
  "session.save.uiLayout": true,
  "session.save.unsavedContent": true,
  "lsp.enabled": true,
  "lsp.completionDebounceMs": 250,
  "lsp.triggerCharacters": ".:/<@(",
  "lsp.hover.enabled": true,
  "lsp.signatureHelp.enabled": true,
  "lsp.signatureHelp.display": "popup",
  "lsp.diagnostics.enabled": true,
  "lsp.diagnostics.showInGutter": true,
  "lsp.diagnostics.underlineErrors": true,
  "lsp.diagnostics.delay": 500
};

export const defaultCommands: Record<string, CommandInfo> = {
  "file.save": {
    "label": "Save",
    "category": "File",
    "description": "Save the current file"
  },
  "file.saveAs": {
    "label": "Save As...",
    "category": "File",
    "description": "Save file with a new name"
  },
  "file.saveAll": {
    "label": "Save All",
    "category": "File",
    "description": "Save all open files"
  },
  "file.open": {
    "label": "Open File...",
    "category": "File",
    "description": "Open a file"
  },
  "file.openFolder": {
    "label": "Open Folder...",
    "category": "File",
    "description": "Open a folder"
  },
  "file.new": {
    "label": "New File",
    "category": "File",
    "description": "Create a new file"
  },
  "file.newFolder": {
    "label": "New Folder",
    "category": "File",
    "description": "Create a new folder"
  },
  "file.close": {
    "label": "Close",
    "category": "File",
    "description": "Close the current file"
  },
  "file.closeAll": {
    "label": "Close All",
    "category": "File",
    "description": "Close all open files"
  },
  "file.closeOthers": {
    "label": "Close Others",
    "category": "File",
    "description": "Close all other files"
  },
  "file.delete": {
    "label": "Delete File",
    "category": "File",
    "description": "Delete the current file"
  },
  "file.rename": {
    "label": "Rename...",
    "category": "File",
    "description": "Rename the current file"
  },
  "file.copyPath": {
    "label": "Copy Path",
    "category": "File",
    "description": "Copy file path to clipboard"
  },
  "file.copyRelativePath": {
    "label": "Copy Relative Path",
    "category": "File",
    "description": "Copy relative path to clipboard"
  },
  "file.revealInFinder": {
    "label": "Reveal in Finder",
    "category": "File",
    "description": "Show file in Finder"
  },
  "edit.undo": {
    "label": "Undo",
    "category": "Edit",
    "description": "Undo last action"
  },
  "edit.redo": {
    "label": "Redo",
    "category": "Edit",
    "description": "Redo last undone action"
  },
  "edit.copy": {
    "label": "Copy",
    "category": "Edit"
  },
  "edit.cut": {
    "label": "Cut",
    "category": "Edit"
  },
  "edit.paste": {
    "label": "Paste",
    "category": "Edit"
  },
  "edit.selectAll": {
    "label": "Select All",
    "category": "Edit"
  },
  "edit.selectNextMatch": {
    "label": "Add Selection to Next Match",
    "category": "Edit"
  },
  "edit.selectAllOccurrences": {
    "label": "Select All Occurrences",
    "category": "Edit"
  },
  "edit.indentLine": {
    "label": "Indent Line",
    "category": "Edit"
  },
  "edit.outdentLine": {
    "label": "Outdent Line",
    "category": "Edit"
  },
  "edit.moveLinesUp": {
    "label": "Move Lines Up",
    "category": "Edit"
  },
  "edit.moveLinesDown": {
    "label": "Move Lines Down",
    "category": "Edit"
  },
  "edit.deleteLine": {
    "label": "Delete Line",
    "category": "Edit"
  },
  "edit.joinLines": {
    "label": "Join Lines",
    "category": "Edit"
  },
  "edit.transformToUppercase": {
    "label": "Transform to Uppercase",
    "category": "Edit"
  },
  "edit.transformToLowercase": {
    "label": "Transform to Lowercase",
    "category": "Edit"
  },
  "edit.transformToTitleCase": {
    "label": "Transform to Title Case",
    "category": "Edit"
  },
  "search.find": {
    "label": "Find",
    "category": "Search"
  },
  "search.replace": {
    "label": "Find and Replace",
    "category": "Search"
  },
  "search.findInFiles": {
    "label": "Find in Files",
    "category": "Search"
  },
  "search.replaceInFiles": {
    "label": "Replace in Files",
    "category": "Search"
  },
  "search.findNext": {
    "label": "Find Next",
    "category": "Search"
  },
  "search.findPrevious": {
    "label": "Find Previous",
    "category": "Search"
  },
  "search.clearHistory": {
    "label": "Clear Search History",
    "category": "Search"
  },
  "editor.gotoLine": {
    "label": "Go to Line...",
    "category": "Go"
  },
  "editor.gotoSymbol": {
    "label": "Go to Symbol in Editor...",
    "category": "Go"
  },
  "editor.gotoWorkspaceSymbol": {
    "label": "Go to Symbol in Workspace...",
    "category": "Go"
  },
  "editor.nextTab": {
    "label": "Next Tab",
    "category": "View"
  },
  "editor.previousTab": {
    "label": "Previous Tab",
    "category": "View"
  },
  "editor.fold": {
    "label": "Fold",
    "category": "Editor"
  },
  "editor.unfold": {
    "label": "Unfold",
    "category": "Editor"
  },
  "editor.foldAll": {
    "label": "Fold All",
    "category": "Editor"
  },
  "editor.unfoldAll": {
    "label": "Unfold All",
    "category": "Editor"
  },
  "editor.foldLevel1": {
    "label": "Fold Level 1",
    "category": "Editor"
  },
  "editor.foldLevel2": {
    "label": "Fold Level 2",
    "category": "Editor"
  },
  "editor.foldLevel3": {
    "label": "Fold Level 3",
    "category": "Editor"
  },
  "editor.toggleComment": {
    "label": "Toggle Line Comment",
    "category": "Editor"
  },
  "editor.toggleBlockComment": {
    "label": "Toggle Block Comment",
    "category": "Editor"
  },
  "editor.commentLine": {
    "label": "Add Line Comment",
    "category": "Editor"
  },
  "editor.uncommentLine": {
    "label": "Remove Line Comment",
    "category": "Editor"
  },
  "editor.selectLine": {
    "label": "Select Line",
    "category": "Editor"
  },
  "editor.duplicateLine": {
    "label": "Duplicate Line",
    "category": "Editor"
  },
  "editor.duplicateSelection": {
    "label": "Duplicate Selection",
    "category": "Editor"
  },
  "editor.addCursorAbove": {
    "label": "Add Cursor Above",
    "category": "Editor"
  },
  "editor.addCursorBelow": {
    "label": "Add Cursor Below",
    "category": "Editor"
  },
  "editor.clearCursors": {
    "label": "Clear Cursors",
    "category": "Editor"
  },
  "editor.formatDocument": {
    "label": "Format Document",
    "category": "Editor"
  },
  "editor.formatSelection": {
    "label": "Format Selection",
    "category": "Editor"
  },
  "editor.sortLinesAscending": {
    "label": "Sort Lines Ascending",
    "category": "Editor"
  },
  "editor.sortLinesDescending": {
    "label": "Sort Lines Descending",
    "category": "Editor"
  },
  "editor.trimTrailingWhitespace": {
    "label": "Trim Trailing Whitespace",
    "category": "Editor"
  },
  "workbench.commandPalette": {
    "label": "Command Palette",
    "category": "View"
  },
  "workbench.quickOpen": {
    "label": "Quick Open",
    "category": "View",
    "description": "Open file by name"
  },
  "workbench.toggleSidebar": {
    "label": "Toggle Sidebar",
    "category": "View"
  },
  "workbench.toggleTerminal": {
    "label": "Toggle Terminal",
    "category": "View"
  },
  "workbench.toggleActivityBar": {
    "label": "Toggle Activity Bar",
    "category": "View"
  },
  "workbench.toggleMinimap": {
    "label": "Toggle Minimap",
    "category": "View"
  },
  "workbench.toggleWordWrap": {
    "label": "Toggle Word Wrap",
    "category": "View"
  },
  "workbench.toggleZenMode": {
    "label": "Toggle Zen Mode",
    "category": "View"
  },
  "workbench.focusNextPane": {
    "label": "Focus Next Pane",
    "category": "View"
  },
  "workbench.focusPreviousPane": {
    "label": "Focus Previous Pane",
    "category": "View"
  },
  "workbench.openSettings": {
    "label": "Open Settings",
    "category": "Preferences"
  },
  "workbench.openKeybindings": {
    "label": "Open Keyboard Shortcuts",
    "category": "Preferences"
  },
  "workbench.quit": {
    "label": "Quit",
    "category": "Application"
  },
  "workbench.reload": {
    "label": "Reload Window",
    "category": "Developer"
  },
  "workbench.toggleDevTools": {
    "label": "Toggle Developer Tools",
    "category": "Developer"
  },
  "view.splitVertical": {
    "label": "Split Editor Right",
    "category": "View"
  },
  "view.splitHorizontal": {
    "label": "Split Editor Down",
    "category": "View"
  },
  "view.closePane": {
    "label": "Close Pane",
    "category": "View"
  },
  "view.focusChat": {
    "label": "Focus Chat",
    "category": "View"
  },
  "view.focusEditor": {
    "label": "Focus Editor",
    "category": "View"
  },
  "view.focusFileTree": {
    "label": "Focus File Explorer",
    "category": "View"
  },
  "view.focusTerminal": {
    "label": "Focus Terminal",
    "category": "View"
  },
  "view.zoomIn": {
    "label": "Zoom In",
    "category": "View"
  },
  "view.zoomOut": {
    "label": "Zoom Out",
    "category": "View"
  },
  "view.resetZoom": {
    "label": "Reset Zoom",
    "category": "View"
  },
  "layout.default": {
    "label": "Default Layout",
    "category": "Layout",
    "description": "Balanced layout with all panels"
  },
  "layout.detachedClaude": {
    "label": "Detached Claude",
    "category": "Layout",
    "description": "File tree, chat stack, and terminal for Claude Code"
  },
  "layout.codeReview": {
    "label": "Code Review",
    "category": "Layout",
    "description": "Side-by-side editor with chat"
  },
  "layout.debug": {
    "label": "Debug",
    "category": "Layout",
    "description": "Terminal and activity prominent"
  },
  "layout.zenEditor": {
    "label": "Zen Mode (Editor)",
    "category": "Layout",
    "description": "Distraction-free editor"
  },
  "layout.zenChat": {
    "label": "Zen Mode (Chat)",
    "category": "Layout",
    "description": "Full-screen AI chat"
  },
  "layout.presentation": {
    "label": "Presentation",
    "category": "Layout",
    "description": "Editor with minimal UI"
  },
  "layout.next": {
    "label": "Next Layout",
    "category": "Layout",
    "description": "Switch to next layout preset"
  },
  "layout.previous": {
    "label": "Previous Layout",
    "category": "Layout",
    "description": "Switch to previous layout preset"
  },
  "terminal.new": {
    "label": "New Terminal",
    "category": "Terminal"
  },
  "terminal.newInPane": {
    "label": "New Terminal in Pane",
    "category": "Terminal"
  },
  "terminal.close": {
    "label": "Close Terminal",
    "category": "Terminal"
  },
  "terminal.closeAll": {
    "label": "Close All Terminals",
    "category": "Terminal"
  },
  "terminal.focus": {
    "label": "Focus Terminal",
    "category": "Terminal"
  },
  "terminal.nextTab": {
    "label": "Next Terminal",
    "category": "Terminal"
  },
  "terminal.previousTab": {
    "label": "Previous Terminal",
    "category": "Terminal"
  },
  "terminal.clear": {
    "label": "Clear Terminal",
    "category": "Terminal"
  },
  "terminal.scrollToTop": {
    "label": "Scroll to Top",
    "category": "Terminal"
  },
  "terminal.scrollToBottom": {
    "label": "Scroll to Bottom",
    "category": "Terminal"
  },
  "terminal.kill": {
    "label": "Kill Terminal Process",
    "category": "Terminal"
  },
  "git.status": {
    "label": "Show Status",
    "category": "Git",
    "description": "Show git status"
  },
  "git.stage": {
    "label": "Stage Changes",
    "category": "Git",
    "description": "Stage current file"
  },
  "git.stageAll": {
    "label": "Stage All Changes",
    "category": "Git",
    "description": "Stage all changes"
  },
  "git.unstage": {
    "label": "Unstage Changes",
    "category": "Git",
    "description": "Unstage current file"
  },
  "git.unstageAll": {
    "label": "Unstage All",
    "category": "Git",
    "description": "Unstage all changes"
  },
  "git.discard": {
    "label": "Discard Changes",
    "category": "Git",
    "description": "Discard changes in file"
  },
  "git.discardAll": {
    "label": "Discard All Changes",
    "category": "Git",
    "description": "Discard all changes"
  },
  "git.commit": {
    "label": "Commit",
    "category": "Git",
    "description": "Commit staged changes"
  },
  "git.commitAmend": {
    "label": "Commit (Amend)",
    "category": "Git",
    "description": "Amend last commit"
  },
  "git.push": {
    "label": "Push",
    "category": "Git",
    "description": "Push to remote"
  },
  "git.pushForce": {
    "label": "Push (Force)",
    "category": "Git",
    "description": "Force push to remote"
  },
  "git.pull": {
    "label": "Pull",
    "category": "Git",
    "description": "Pull from remote"
  },
  "git.pullRebase": {
    "label": "Pull (Rebase)",
    "category": "Git",
    "description": "Pull with rebase"
  },
  "git.fetch": {
    "label": "Fetch",
    "category": "Git",
    "description": "Fetch from remote"
  },
  "git.fetchAll": {
    "label": "Fetch All",
    "category": "Git",
    "description": "Fetch from all remotes"
  },
  "git.stash": {
    "label": "Stash",
    "category": "Git",
    "description": "Stash changes"
  },
  "git.stashPop": {
    "label": "Pop Stash",
    "category": "Git",
    "description": "Pop latest stash"
  },
  "git.stashApply": {
    "label": "Apply Stash",
    "category": "Git",
    "description": "Apply stash without removing"
  },
  "git.stashDrop": {
    "label": "Drop Stash",
    "category": "Git",
    "description": "Drop a stash"
  },
  "git.stashList": {
    "label": "List Stashes",
    "category": "Git",
    "description": "Show all stashes"
  },
  "git.log": {
    "label": "View Log",
    "category": "Git",
    "description": "Show commit history"
  },
  "git.logFile": {
    "label": "View File History",
    "category": "Git",
    "description": "Show file commit history"
  },
  "git.blame": {
    "label": "Toggle Blame",
    "category": "Git",
    "description": "Show line-by-line blame"
  },
  "git.diff": {
    "label": "View Diff",
    "category": "Git",
    "description": "Show diff for file"
  },
  "git.diffStaged": {
    "label": "View Staged Diff",
    "category": "Git",
    "description": "Show staged changes"
  },
  "git.branches": {
    "label": "List Branches",
    "category": "Git",
    "description": "Show all branches"
  },
  "git.createBranch": {
    "label": "Create Branch...",
    "category": "Git",
    "description": "Create a new branch"
  },
  "git.switchBranch": {
    "label": "Switch Branch...",
    "category": "Git",
    "description": "Switch to another branch"
  },
  "git.deleteBranch": {
    "label": "Delete Branch...",
    "category": "Git",
    "description": "Delete a branch"
  },
  "git.renameBranch": {
    "label": "Rename Branch...",
    "category": "Git",
    "description": "Rename current branch"
  },
  "git.merge": {
    "label": "Merge Branch...",
    "category": "Git",
    "description": "Merge a branch"
  },
  "git.rebase": {
    "label": "Rebase...",
    "category": "Git",
    "description": "Rebase onto branch"
  },
  "git.abortMerge": {
    "label": "Abort Merge",
    "category": "Git",
    "description": "Abort current merge"
  },
  "git.abortRebase": {
    "label": "Abort Rebase",
    "category": "Git",
    "description": "Abort current rebase"
  },
  "git.continueRebase": {
    "label": "Continue Rebase",
    "category": "Git",
    "description": "Continue rebase after resolving conflicts"
  },
  "git.conflicts": {
    "label": "View Conflicts",
    "category": "Git",
    "description": "Show conflicted files"
  },
  "git.remotes": {
    "label": "Manage Remotes",
    "category": "Git",
    "description": "View and manage remotes"
  },
  "git.tags": {
    "label": "List Tags",
    "category": "Git",
    "description": "Show all tags"
  },
  "git.createTag": {
    "label": "Create Tag...",
    "category": "Git",
    "description": "Create a new tag"
  },
  "git.checkout": {
    "label": "Checkout...",
    "category": "Git",
    "description": "Checkout a commit or branch"
  },
  "git.cherryPick": {
    "label": "Cherry Pick...",
    "category": "Git",
    "description": "Cherry pick a commit"
  },
  "git.revert": {
    "label": "Revert Commit...",
    "category": "Git",
    "description": "Revert a commit"
  },
  "git.reset": {
    "label": "Reset...",
    "category": "Git",
    "description": "Reset to a commit"
  },
  "git.clean": {
    "label": "Clean Untracked",
    "category": "Git",
    "description": "Remove untracked files"
  },
  "git.focusPanel": {
    "label": "Focus Git Panel",
    "category": "Git"
  },
  "git.refresh": {
    "label": "Refresh",
    "category": "Git",
    "description": "Refresh git status"
  },
  "ai.newChat": {
    "label": "New AI Chat",
    "category": "AI"
  },
  "ai.toggleChat": {
    "label": "Toggle AI Chat",
    "category": "AI"
  },
  "ai.toggleServiceChat": {
    "label": "Toggle Service Chat",
    "category": "AI"
  },
  "ai.clearChat": {
    "label": "Clear Chat History",
    "category": "AI"
  },
  "ai.showPermissions": {
    "label": "Show Pending Permissions",
    "category": "AI"
  },
  "ai.approveAll": {
    "label": "Approve All Pending",
    "category": "AI"
  },
  "ai.denyAll": {
    "label": "Deny All Pending",
    "category": "AI"
  },
  "ai.cancelRequest": {
    "label": "Cancel Current Request",
    "category": "AI"
  },
  "ai.regenerate": {
    "label": "Regenerate Response",
    "category": "AI"
  },
  "ai.copyLastResponse": {
    "label": "Copy Last Response",
    "category": "AI"
  },
  "ai.exportChat": {
    "label": "Export Chat",
    "category": "AI"
  },
  "session.save": {
    "label": "Save Session",
    "category": "Session"
  },
  "session.saveAs": {
    "label": "Save Session As...",
    "category": "Session"
  },
  "session.open": {
    "label": "Open Session...",
    "category": "Session"
  },
  "session.delete": {
    "label": "Delete Session...",
    "category": "Session"
  },
  "session.list": {
    "label": "List Sessions",
    "category": "Session"
  },
  "theme.select": {
    "label": "Color Theme",
    "category": "Preferences",
    "description": "Select a color theme"
  },
  "theme.next": {
    "label": "Next Theme",
    "category": "Preferences"
  },
  "theme.previous": {
    "label": "Previous Theme",
    "category": "Preferences"
  },
  "theme.toggleDarkMode": {
    "label": "Toggle Dark Mode",
    "category": "Preferences"
  },
  "lsp.showHover": {
    "label": "Show Hover",
    "category": "Editor"
  },
  "lsp.goToDefinition": {
    "label": "Go to Definition",
    "category": "Go"
  },
  "lsp.goToDeclaration": {
    "label": "Go to Declaration",
    "category": "Go"
  },
  "lsp.goToTypeDefinition": {
    "label": "Go to Type Definition",
    "category": "Go"
  },
  "lsp.goToImplementation": {
    "label": "Go to Implementation",
    "category": "Go"
  },
  "lsp.findReferences": {
    "label": "Find All References",
    "category": "Go"
  },
  "lsp.rename": {
    "label": "Rename Symbol",
    "category": "Editor"
  },
  "lsp.triggerCompletion": {
    "label": "Trigger Completion",
    "category": "Editor"
  },
  "lsp.triggerSignatureHelp": {
    "label": "Trigger Signature Help",
    "category": "Editor"
  },
  "lsp.restartServer": {
    "label": "Restart Language Server",
    "category": "Developer"
  },
  "lsp.showDiagnostics": {
    "label": "Show Problems",
    "category": "View"
  },
  "lsp.nextDiagnostic": {
    "label": "Go to Next Problem",
    "category": "Go"
  },
  "lsp.previousDiagnostic": {
    "label": "Go to Previous Problem",
    "category": "Go"
  },
  "database.newQuery": {
    "label": "New Query",
    "category": "Database"
  },
  "database.executeQuery": {
    "label": "Execute Query",
    "category": "Database"
  },
  "database.executeSelection": {
    "label": "Execute Selection",
    "category": "Database"
  },
  "database.connect": {
    "label": "Connect to Database",
    "category": "Database"
  },
  "database.disconnect": {
    "label": "Disconnect",
    "category": "Database"
  },
  "database.newConnection": {
    "label": "New Connection...",
    "category": "Database"
  },
  "database.editConnection": {
    "label": "Edit Connection...",
    "category": "Database"
  },
  "database.deleteConnection": {
    "label": "Delete Connection",
    "category": "Database"
  },
  "database.viewHistory": {
    "label": "Query History",
    "category": "Database"
  },
  "database.browseSchema": {
    "label": "Browse Schema",
    "category": "Database"
  },
  "database.exportResults": {
    "label": "Export Results",
    "category": "Database"
  },
  "database.describeTable": {
    "label": "Describe Table",
    "category": "Database"
  },
  "ensemble.open": {
    "label": "Open Ensemble",
    "category": "AI"
  },
  "ensemble.toggle": {
    "label": "Toggle Ensemble",
    "category": "AI"
  },
  "ensemble.start": {
    "label": "Start Ensemble Session",
    "category": "AI"
  },
  "ensemble.abort": {
    "label": "Abort Ensemble",
    "category": "AI"
  },
  "ensemble.pause": {
    "label": "Pause Ensemble",
    "category": "AI"
  },
  "ensemble.resume": {
    "label": "Resume Ensemble",
    "category": "AI"
  },
  "secrets.setAnthropicApiKey": {
    "label": "Set Anthropic API Key",
    "category": "Secrets"
  },
  "secrets.setOpenAIApiKey": {
    "label": "Set OpenAI API Key",
    "category": "Secrets"
  },
  "secrets.setGeminiApiKey": {
    "label": "Set Gemini API Key",
    "category": "Secrets"
  },
  "secrets.manage": {
    "label": "Manage Secrets",
    "category": "Secrets"
  },
  "models.refresh": {
    "label": "Refresh Models",
    "category": "AI"
  },
  "models.select": {
    "label": "Select Model",
    "category": "AI"
  },
  "debug.start": {
    "label": "Start Debugging",
    "category": "Debug"
  },
  "debug.stop": {
    "label": "Stop Debugging",
    "category": "Debug"
  },
  "debug.restart": {
    "label": "Restart Debugging",
    "category": "Debug"
  },
  "debug.stepOver": {
    "label": "Step Over",
    "category": "Debug"
  },
  "debug.stepInto": {
    "label": "Step Into",
    "category": "Debug"
  },
  "debug.stepOut": {
    "label": "Step Out",
    "category": "Debug"
  },
  "debug.continue": {
    "label": "Continue",
    "category": "Debug"
  },
  "debug.toggleBreakpoint": {
    "label": "Toggle Breakpoint",
    "category": "Debug"
  },
  "help.documentation": {
    "label": "Documentation",
    "category": "Help"
  },
  "help.reportIssue": {
    "label": "Report Issue",
    "category": "Help"
  },
  "help.about": {
    "label": "About",
    "category": "Help"
  },
  "help.keyboardShortcuts": {
    "label": "Keyboard Shortcuts Reference",
    "category": "Help"
  },
  "help.checkForUpdates": {
    "label": "Check for Updates",
    "category": "Help"
  }
};

export const defaultThemes: Record<string, Theme> = {
  "catppuccin-mocha": {
    "name": "Catppuccin Mocha",
    "type": "dark",
    "colors": {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#313244",
      "editor.selectionBackground": "#585b70",
      "editor.findMatchBackground": "#45475a",
      "editor.findMatchHighlightBackground": "#fab38780",
      "editorBracketMatch.background": "#313244",
      "editorCursor.foreground": "#f5e0dc",
      "editorLineNumber.foreground": "#585b70",
      "editorLineNumber.activeForeground": "#cdd6f4",
      "editorGutter.background": "#1e1e2e",
      "editorGutter.addedBackground": "#a6e3a1",
      "editorGutter.modifiedBackground": "#f9e2af",
      "editorGutter.deletedBackground": "#f38ba8",
      "statusBar.background": "#181825",
      "statusBar.foreground": "#cdd6f4",
      "tab.activeBackground": "#1e1e2e",
      "tab.activeForeground": "#cdd6f4",
      "tab.inactiveBackground": "#181825",
      "tab.inactiveForeground": "#7f849c",
      "tab.border": "#11111b",
      "sideBar.background": "#181825",
      "sideBar.foreground": "#cdd6f4",
      "sideBarTitle.foreground": "#cdd6f4",
      "list.activeSelectionBackground": "#313244",
      "list.activeSelectionForeground": "#cdd6f4",
      "list.hoverBackground": "#313244",
      "terminal.background": "#1e1e2e",
      "terminal.foreground": "#cdd6f4",
      "input.background": "#181825",
      "input.foreground": "#cdd6f4",
      "input.border": "#313244",
      "focusBorder": "#89b4fa",
      "editorWidget.background": "#11111b",
      "editorWidget.foreground": "#cdd6f4",
      "editorWidget.border": "#45475a"
    },
    "tokenColors": [
      {
        "name": "Comment",
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#585b70",
          "fontStyle": "italic"
        }
      },
      {
        "name": "String",
        "scope": [
          "string",
          "string.quoted"
        ],
        "settings": {
          "foreground": "#a6e3a1"
        }
      },
      {
        "name": "Number",
        "scope": [
          "constant.numeric"
        ],
        "settings": {
          "foreground": "#fab387"
        }
      },
      {
        "name": "Boolean",
        "scope": [
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#fab387"
        }
      },
      {
        "name": "Null/Undefined",
        "scope": [
          "constant.language.null",
          "constant.language.undefined"
        ],
        "settings": {
          "foreground": "#fab387"
        }
      },
      {
        "name": "Keyword",
        "scope": [
          "keyword",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#cba6f7"
        }
      },
      {
        "name": "Keyword Control",
        "scope": [
          "keyword.control"
        ],
        "settings": {
          "foreground": "#cba6f7"
        }
      },
      {
        "name": "Operator",
        "scope": [
          "keyword.operator"
        ],
        "settings": {
          "foreground": "#94e2d5"
        }
      },
      {
        "name": "Function",
        "scope": [
          "entity.name.function",
          "meta.function-call",
          "support.function"
        ],
        "settings": {
          "foreground": "#89b4fa"
        }
      },
      {
        "name": "Function Parameter",
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#eba0ac",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Variable",
        "scope": [
          "variable",
          "variable.other"
        ],
        "settings": {
          "foreground": "#cdd6f4"
        }
      },
      {
        "name": "Class",
        "scope": [
          "entity.name.class",
          "entity.name.type.class",
          "support.class"
        ],
        "settings": {
          "foreground": "#f9e2af"
        }
      },
      {
        "name": "Type",
        "scope": [
          "entity.name.type",
          "support.type"
        ],
        "settings": {
          "foreground": "#f9e2af"
        }
      },
      {
        "name": "Interface",
        "scope": [
          "entity.name.type.interface"
        ],
        "settings": {
          "foreground": "#f9e2af"
        }
      },
      {
        "name": "Property",
        "scope": [
          "variable.other.property",
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#89b4fa"
        }
      },
      {
        "name": "Constant",
        "scope": [
          "variable.other.constant"
        ],
        "settings": {
          "foreground": "#fab387"
        }
      },
      {
        "name": "Tag",
        "scope": [
          "entity.name.tag"
        ],
        "settings": {
          "foreground": "#cba6f7"
        }
      },
      {
        "name": "Attribute",
        "scope": [
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#f9e2af",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Punctuation",
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#cdd6f4"
        }
      },
      {
        "name": "Bracket",
        "scope": [
          "punctuation.definition.block",
          "punctuation.definition.parameters"
        ],
        "settings": {
          "foreground": "#cdd6f4"
        }
      },
      {
        "name": "Import/Export",
        "scope": [
          "keyword.control.import",
          "keyword.control.export",
          "keyword.control.from"
        ],
        "settings": {
          "foreground": "#cba6f7"
        }
      },
      {
        "name": "Regex",
        "scope": [
          "string.regexp"
        ],
        "settings": {
          "foreground": "#f5c2e7"
        }
      },
      {
        "name": "Escape Character",
        "scope": [
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#f5c2e7"
        }
      },
      {
        "name": "This/Self",
        "scope": [
          "variable.language.this",
          "variable.language.self"
        ],
        "settings": {
          "foreground": "#f38ba8"
        }
      },
      {
        "name": "Markdown Heading",
        "scope": [
          "markup.heading",
          "entity.name.section"
        ],
        "settings": {
          "foreground": "#f38ba8",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Bold",
        "scope": [
          "markup.bold"
        ],
        "settings": {
          "foreground": "#f38ba8",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Italic",
        "scope": [
          "markup.italic"
        ],
        "settings": {
          "foreground": "#f38ba8",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Markdown Code",
        "scope": [
          "markup.inline.raw",
          "markup.fenced_code"
        ],
        "settings": {
          "foreground": "#a6e3a1"
        }
      },
      {
        "name": "Markdown Link",
        "scope": [
          "markup.underline.link"
        ],
        "settings": {
          "foreground": "#89b4fa"
        }
      },
      {
        "name": "JSON Key",
        "scope": [
          "support.type.property-name.json"
        ],
        "settings": {
          "foreground": "#89b4fa"
        }
      }
    ]
  },
  "catppuccin-macchiato": {
    "name": "Catppuccin Macchiato",
    "type": "dark",
    "colors": {
      "editor.background": "#24273a",
      "editor.foreground": "#cad3f5",
      "editor.lineHighlightBackground": "#363a4f",
      "editor.selectionBackground": "#5b6078",
      "editor.findMatchBackground": "#494d64",
      "editor.findMatchHighlightBackground": "#f5a97f80",
      "editorBracketMatch.background": "#363a4f",
      "editorCursor.foreground": "#f4dbd6",
      "editorLineNumber.foreground": "#5b6078",
      "editorLineNumber.activeForeground": "#cad3f5",
      "editorGutter.background": "#24273a",
      "editorGutter.addedBackground": "#a6da95",
      "editorGutter.modifiedBackground": "#eed49f",
      "editorGutter.deletedBackground": "#ed8796",
      "statusBar.background": "#1e2030",
      "statusBar.foreground": "#cad3f5",
      "tab.activeBackground": "#24273a",
      "tab.activeForeground": "#cad3f5",
      "tab.inactiveBackground": "#1e2030",
      "tab.inactiveForeground": "#8087a2",
      "tab.border": "#181926",
      "sideBar.background": "#1e2030",
      "sideBar.foreground": "#cad3f5",
      "sideBarTitle.foreground": "#cad3f5",
      "list.activeSelectionBackground": "#363a4f",
      "list.activeSelectionForeground": "#cad3f5",
      "list.hoverBackground": "#363a4f",
      "terminal.background": "#24273a",
      "terminal.foreground": "#cad3f5",
      "input.background": "#1e2030",
      "input.foreground": "#cad3f5",
      "input.border": "#363a4f",
      "focusBorder": "#8aadf4",
      "editorWidget.background": "#181926",
      "editorWidget.foreground": "#cad3f5",
      "editorWidget.border": "#494d64"
    },
    "tokenColors": [
      {
        "name": "Comment",
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#5b6078",
          "fontStyle": "italic"
        }
      },
      {
        "name": "String",
        "scope": [
          "string",
          "string.quoted"
        ],
        "settings": {
          "foreground": "#a6da95"
        }
      },
      {
        "name": "Number",
        "scope": [
          "constant.numeric"
        ],
        "settings": {
          "foreground": "#f5a97f"
        }
      },
      {
        "name": "Boolean",
        "scope": [
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#f5a97f"
        }
      },
      {
        "name": "Null/Undefined",
        "scope": [
          "constant.language.null",
          "constant.language.undefined"
        ],
        "settings": {
          "foreground": "#f5a97f"
        }
      },
      {
        "name": "Keyword",
        "scope": [
          "keyword",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#c6a0f6"
        }
      },
      {
        "name": "Keyword Control",
        "scope": [
          "keyword.control"
        ],
        "settings": {
          "foreground": "#c6a0f6"
        }
      },
      {
        "name": "Operator",
        "scope": [
          "keyword.operator"
        ],
        "settings": {
          "foreground": "#8bd5ca"
        }
      },
      {
        "name": "Function",
        "scope": [
          "entity.name.function",
          "meta.function-call",
          "support.function"
        ],
        "settings": {
          "foreground": "#8aadf4"
        }
      },
      {
        "name": "Function Parameter",
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#ee99a0",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Variable",
        "scope": [
          "variable",
          "variable.other"
        ],
        "settings": {
          "foreground": "#cad3f5"
        }
      },
      {
        "name": "Class",
        "scope": [
          "entity.name.class",
          "entity.name.type.class",
          "support.class"
        ],
        "settings": {
          "foreground": "#eed49f"
        }
      },
      {
        "name": "Type",
        "scope": [
          "entity.name.type",
          "support.type"
        ],
        "settings": {
          "foreground": "#eed49f"
        }
      },
      {
        "name": "Interface",
        "scope": [
          "entity.name.type.interface"
        ],
        "settings": {
          "foreground": "#eed49f"
        }
      },
      {
        "name": "Property",
        "scope": [
          "variable.other.property",
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#8aadf4"
        }
      },
      {
        "name": "Constant",
        "scope": [
          "variable.other.constant"
        ],
        "settings": {
          "foreground": "#f5a97f"
        }
      },
      {
        "name": "Tag",
        "scope": [
          "entity.name.tag"
        ],
        "settings": {
          "foreground": "#c6a0f6"
        }
      },
      {
        "name": "Attribute",
        "scope": [
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#eed49f",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Punctuation",
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#cad3f5"
        }
      },
      {
        "name": "Bracket",
        "scope": [
          "punctuation.definition.block",
          "punctuation.definition.parameters"
        ],
        "settings": {
          "foreground": "#cad3f5"
        }
      },
      {
        "name": "Import/Export",
        "scope": [
          "keyword.control.import",
          "keyword.control.export",
          "keyword.control.from"
        ],
        "settings": {
          "foreground": "#c6a0f6"
        }
      },
      {
        "name": "Regex",
        "scope": [
          "string.regexp"
        ],
        "settings": {
          "foreground": "#f5bde6"
        }
      },
      {
        "name": "Escape Character",
        "scope": [
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#f5bde6"
        }
      },
      {
        "name": "This/Self",
        "scope": [
          "variable.language.this",
          "variable.language.self"
        ],
        "settings": {
          "foreground": "#ed8796"
        }
      },
      {
        "name": "Markdown Heading",
        "scope": [
          "markup.heading",
          "entity.name.section"
        ],
        "settings": {
          "foreground": "#ed8796",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Bold",
        "scope": [
          "markup.bold"
        ],
        "settings": {
          "foreground": "#ed8796",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Italic",
        "scope": [
          "markup.italic"
        ],
        "settings": {
          "foreground": "#ed8796",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Markdown Code",
        "scope": [
          "markup.inline.raw",
          "markup.fenced_code"
        ],
        "settings": {
          "foreground": "#a6da95"
        }
      },
      {
        "name": "Markdown Link",
        "scope": [
          "markup.underline.link"
        ],
        "settings": {
          "foreground": "#8aadf4"
        }
      },
      {
        "name": "JSON Key",
        "scope": [
          "support.type.property-name.json"
        ],
        "settings": {
          "foreground": "#8aadf4"
        }
      }
    ]
  },
  "catppuccin-frappe": {
    "name": "Catppuccin Frappé",
    "type": "dark",
    "colors": {
      "editor.background": "#303446",
      "editor.foreground": "#c6d0f5",
      "editor.lineHighlightBackground": "#414559",
      "editor.selectionBackground": "#626880",
      "editor.findMatchBackground": "#51576d",
      "editor.findMatchHighlightBackground": "#ef9f7680",
      "editorBracketMatch.background": "#9da2b8",
      "editorCursor.foreground": "#f2d5cf",
      "editorLineNumber.foreground": "#626880",
      "editorLineNumber.activeForeground": "#c6d0f5",
      "editorGutter.background": "#303446",
      "editorGutter.addedBackground": "#a6d189",
      "editorGutter.modifiedBackground": "#e5c890",
      "editorGutter.deletedBackground": "#e78284",
      "statusBar.background": "#292c3c",
      "statusBar.foreground": "#c6d0f5",
      "tab.activeBackground": "#303446",
      "tab.activeForeground": "#c6d0f5",
      "tab.inactiveBackground": "#292c3c",
      "tab.inactiveForeground": "#838ba7",
      "tab.border": "#232634",
      "sideBar.background": "#292c3c",
      "sideBar.foreground": "#c6d0f5",
      "sideBarTitle.foreground": "#c6d0f5",
      "list.activeSelectionBackground": "#414559",
      "list.activeSelectionForeground": "#c6d0f5",
      "list.hoverBackground": "#414559",
      "terminal.background": "#303446",
      "terminal.foreground": "#c6d0f5",
      "input.background": "#292c3c",
      "input.foreground": "#c6d0f5",
      "input.border": "#414559",
      "focusBorder": "#8caaee",
      "editorWidget.background": "#232634",
      "editorWidget.foreground": "#c6d0f5",
      "editorWidget.border": "#51576d"
    },
    "tokenColors": [
      {
        "name": "Comment",
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#626880",
          "fontStyle": "italic"
        }
      },
      {
        "name": "String",
        "scope": [
          "string",
          "string.quoted"
        ],
        "settings": {
          "foreground": "#a6d189"
        }
      },
      {
        "name": "Number",
        "scope": [
          "constant.numeric"
        ],
        "settings": {
          "foreground": "#ef9f76"
        }
      },
      {
        "name": "Boolean",
        "scope": [
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#ef9f76"
        }
      },
      {
        "name": "Null/Undefined",
        "scope": [
          "constant.language.null",
          "constant.language.undefined"
        ],
        "settings": {
          "foreground": "#ef9f76"
        }
      },
      {
        "name": "Keyword",
        "scope": [
          "keyword",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#ca9ee6"
        }
      },
      {
        "name": "Keyword Control",
        "scope": [
          "keyword.control"
        ],
        "settings": {
          "foreground": "#ca9ee6"
        }
      },
      {
        "name": "Operator",
        "scope": [
          "keyword.operator"
        ],
        "settings": {
          "foreground": "#99d1db"
        }
      },
      {
        "name": "Function",
        "scope": [
          "entity.name.function",
          "meta.function-call",
          "support.function"
        ],
        "settings": {
          "foreground": "#8caaee"
        }
      },
      {
        "name": "Function Parameter",
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#eebebe",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Variable",
        "scope": [
          "variable",
          "variable.other"
        ],
        "settings": {
          "foreground": "#c6d0f5"
        }
      },
      {
        "name": "Class",
        "scope": [
          "entity.name.class",
          "entity.name.type.class",
          "support.class"
        ],
        "settings": {
          "foreground": "#e5c890"
        }
      },
      {
        "name": "Type",
        "scope": [
          "entity.name.type",
          "support.type"
        ],
        "settings": {
          "foreground": "#e5c890"
        }
      },
      {
        "name": "Interface",
        "scope": [
          "entity.name.type.interface"
        ],
        "settings": {
          "foreground": "#e5c890"
        }
      },
      {
        "name": "Property",
        "scope": [
          "variable.other.property",
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#8caaee"
        }
      },
      {
        "name": "Constant",
        "scope": [
          "variable.other.constant"
        ],
        "settings": {
          "foreground": "#ef9f76"
        }
      },
      {
        "name": "Tag",
        "scope": [
          "entity.name.tag"
        ],
        "settings": {
          "foreground": "#ca9ee6"
        }
      },
      {
        "name": "Attribute",
        "scope": [
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#e5c890",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Punctuation",
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#c6d0f5"
        }
      },
      {
        "name": "Bracket",
        "scope": [
          "punctuation.definition.block",
          "punctuation.definition.parameters"
        ],
        "settings": {
          "foreground": "#c6d0f5"
        }
      },
      {
        "name": "Import/Export",
        "scope": [
          "keyword.control.import",
          "keyword.control.export",
          "keyword.control.from"
        ],
        "settings": {
          "foreground": "#ca9ee6"
        }
      },
      {
        "name": "Regex",
        "scope": [
          "string.regexp"
        ],
        "settings": {
          "foreground": "#f4b8e4"
        }
      },
      {
        "name": "Escape Character",
        "scope": [
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#f4b8e4"
        }
      },
      {
        "name": "This/Self",
        "scope": [
          "variable.language.this",
          "variable.language.self"
        ],
        "settings": {
          "foreground": "#e78284"
        }
      },
      {
        "name": "Markdown Heading",
        "scope": [
          "markup.heading",
          "entity.name.section"
        ],
        "settings": {
          "foreground": "#e78284",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Bold",
        "scope": [
          "markup.bold"
        ],
        "settings": {
          "foreground": "#e78284",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Italic",
        "scope": [
          "markup.italic"
        ],
        "settings": {
          "foreground": "#e78284",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Markdown Code",
        "scope": [
          "markup.inline.raw",
          "markup.fenced_code"
        ],
        "settings": {
          "foreground": "#a6d189"
        }
      },
      {
        "name": "Markdown Link",
        "scope": [
          "markup.underline.link"
        ],
        "settings": {
          "foreground": "#8caaee"
        }
      },
      {
        "name": "JSON Key",
        "scope": [
          "support.type.property-name.json"
        ],
        "settings": {
          "foreground": "#8caaee"
        }
      }
    ]
  },
  "catppuccin-latte": {
    "name": "Catppuccin Latte",
    "type": "light",
    "colors": {
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "editor.lineHighlightBackground": "#e6e9ef",
      "editor.selectionBackground": "#acb0be",
      "editor.findMatchBackground": "#bcc0cc",
      "editor.findMatchHighlightBackground": "#fe640b80",
      "editorBracketMatch.background": "#e6e9ef",
      "editorCursor.foreground": "#dc8a78",
      "editorLineNumber.foreground": "#acb0be",
      "editorLineNumber.activeForeground": "#4c4f69",
      "editorGutter.background": "#eff1f5",
      "editorGutter.addedBackground": "#40a02b",
      "editorGutter.modifiedBackground": "#df8e1d",
      "editorGutter.deletedBackground": "#d20f39",
      "statusBar.background": "#dce0e8",
      "statusBar.foreground": "#4c4f69",
      "tab.activeBackground": "#eff1f5",
      "tab.activeForeground": "#4c4f69",
      "tab.inactiveBackground": "#dce0e8",
      "tab.inactiveForeground": "#8c8fa1",
      "tab.border": "#ccd0da",
      "sideBar.background": "#dce0e8",
      "sideBar.foreground": "#4c4f69",
      "sideBarTitle.foreground": "#4c4f69",
      "list.activeSelectionBackground": "#e6e9ef",
      "list.activeSelectionForeground": "#4c4f69",
      "list.hoverBackground": "#e6e9ef",
      "terminal.background": "#eff1f5",
      "terminal.foreground": "#4c4f69",
      "input.background": "#dce0e8",
      "input.foreground": "#4c4f69",
      "input.border": "#e6e9ef",
      "focusBorder": "#1e66f5",
      "editorWidget.background": "#e6e9ef",
      "editorWidget.foreground": "#4c4f69",
      "editorWidget.border": "#bcc0cc"
    },
    "tokenColors": [
      {
        "name": "Comment",
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#9ca0b0",
          "fontStyle": "italic"
        }
      },
      {
        "name": "String",
        "scope": [
          "string",
          "string.quoted"
        ],
        "settings": {
          "foreground": "#40a02b"
        }
      },
      {
        "name": "Number",
        "scope": [
          "constant.numeric"
        ],
        "settings": {
          "foreground": "#fe640b"
        }
      },
      {
        "name": "Boolean",
        "scope": [
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#fe640b"
        }
      },
      {
        "name": "Null/Undefined",
        "scope": [
          "constant.language.null",
          "constant.language.undefined"
        ],
        "settings": {
          "foreground": "#fe640b"
        }
      },
      {
        "name": "Keyword",
        "scope": [
          "keyword",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#8839ef"
        }
      },
      {
        "name": "Keyword Control",
        "scope": [
          "keyword.control"
        ],
        "settings": {
          "foreground": "#8839ef"
        }
      },
      {
        "name": "Operator",
        "scope": [
          "keyword.operator"
        ],
        "settings": {
          "foreground": "#179299"
        }
      },
      {
        "name": "Function",
        "scope": [
          "entity.name.function",
          "meta.function-call",
          "support.function"
        ],
        "settings": {
          "foreground": "#1e66f5"
        }
      },
      {
        "name": "Function Parameter",
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#e64553",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Variable",
        "scope": [
          "variable",
          "variable.other"
        ],
        "settings": {
          "foreground": "#4c4f69"
        }
      },
      {
        "name": "Class",
        "scope": [
          "entity.name.class",
          "entity.name.type.class",
          "support.class"
        ],
        "settings": {
          "foreground": "#df8e1d"
        }
      },
      {
        "name": "Type",
        "scope": [
          "entity.name.type",
          "support.type"
        ],
        "settings": {
          "foreground": "#df8e1d"
        }
      },
      {
        "name": "Interface",
        "scope": [
          "entity.name.type.interface"
        ],
        "settings": {
          "foreground": "#df8e1d"
        }
      },
      {
        "name": "Property",
        "scope": [
          "variable.other.property",
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#1e66f5"
        }
      },
      {
        "name": "Constant",
        "scope": [
          "variable.other.constant"
        ],
        "settings": {
          "foreground": "#fe640b"
        }
      },
      {
        "name": "Tag",
        "scope": [
          "entity.name.tag"
        ],
        "settings": {
          "foreground": "#8839ef"
        }
      },
      {
        "name": "Attribute",
        "scope": [
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#df8e1d",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Punctuation",
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#4c4f69"
        }
      },
      {
        "name": "Bracket",
        "scope": [
          "punctuation.definition.block",
          "punctuation.definition.parameters"
        ],
        "settings": {
          "foreground": "#4c4f69"
        }
      },
      {
        "name": "Import/Export",
        "scope": [
          "keyword.control.import",
          "keyword.control.export",
          "keyword.control.from"
        ],
        "settings": {
          "foreground": "#8839ef"
        }
      },
      {
        "name": "Regex",
        "scope": [
          "string.regexp"
        ],
        "settings": {
          "foreground": "#ea76cb"
        }
      },
      {
        "name": "Escape Character",
        "scope": [
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#ea76cb"
        }
      },
      {
        "name": "This/Self",
        "scope": [
          "variable.language.this",
          "variable.language.self"
        ],
        "settings": {
          "foreground": "#d20f39"
        }
      },
      {
        "name": "Markdown Heading",
        "scope": [
          "markup.heading",
          "entity.name.section"
        ],
        "settings": {
          "foreground": "#d20f39",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Bold",
        "scope": [
          "markup.bold"
        ],
        "settings": {
          "foreground": "#d20f39",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Italic",
        "scope": [
          "markup.italic"
        ],
        "settings": {
          "foreground": "#d20f39",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Markdown Code",
        "scope": [
          "markup.inline.raw",
          "markup.fenced_code"
        ],
        "settings": {
          "foreground": "#40a02b"
        }
      },
      {
        "name": "Markdown Link",
        "scope": [
          "markup.underline.link"
        ],
        "settings": {
          "foreground": "#1e66f5"
        }
      },
      {
        "name": "JSON Key",
        "scope": [
          "support.type.property-name.json"
        ],
        "settings": {
          "foreground": "#1e66f5"
        }
      }
    ]
  },
  "one-dark": {
    "name": "One Dark",
    "type": "dark",
    "colors": {
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      "editor.lineHighlightBackground": "#2c313c",
      "editor.selectionBackground": "#3e4451",
      "editor.findMatchBackground": "#515c6a",
      "editor.findMatchHighlightBackground": "#ea5c0080",
      "editorBracketMatch.background": "#3a3f4a",
      "editorCursor.foreground": "#528bff",
      "editorLineNumber.foreground": "#495162",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorGutter.background": "#282c34",
      "editorGutter.addedBackground": "#98c379",
      "editorGutter.modifiedBackground": "#e5c07b",
      "editorGutter.deletedBackground": "#e06c75",
      "statusBar.background": "#21252b",
      "statusBar.foreground": "#9da5b4",
      "tab.activeBackground": "#282c34",
      "tab.activeForeground": "#abb2bf",
      "tab.inactiveBackground": "#21252b",
      "tab.inactiveForeground": "#5c6370",
      "tab.border": "#181a1f",
      "sideBar.background": "#21252b",
      "sideBar.foreground": "#abb2bf",
      "sideBarTitle.foreground": "#abb2bf",
      "list.activeSelectionBackground": "#2c313a",
      "list.activeSelectionForeground": "#d7dae0",
      "list.hoverBackground": "#2c313a",
      "terminal.background": "#1e2127",
      "terminal.foreground": "#abb2bf",
      "input.background": "#1d1f23",
      "input.foreground": "#abb2bf",
      "input.border": "#3a3f4b",
      "focusBorder": "#528bff",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#4e566680",
      "scrollbarSlider.hoverBackground": "#5a637580",
      "editorWidget.background": "#181a1f",
      "editorWidget.foreground": "#abb2bf",
      "editorWidget.border": "#3e4451"
    },
    "tokenColors": [
      {
        "name": "Comment",
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#5c6370",
          "fontStyle": "italic"
        }
      },
      {
        "name": "String",
        "scope": [
          "string",
          "string.quoted"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "name": "Number",
        "scope": [
          "constant.numeric"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "name": "Boolean",
        "scope": [
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "name": "Null/Undefined",
        "scope": [
          "constant.language.null",
          "constant.language.undefined"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "name": "Keyword",
        "scope": [
          "keyword",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "name": "Keyword Control",
        "scope": [
          "keyword.control"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "name": "Operator",
        "scope": [
          "keyword.operator"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "name": "Function",
        "scope": [
          "entity.name.function",
          "meta.function-call"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "name": "Function Parameter",
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "name": "Variable",
        "scope": [
          "variable",
          "variable.other"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "name": "Class",
        "scope": [
          "entity.name.class",
          "entity.name.type.class",
          "support.class"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "name": "Type",
        "scope": [
          "entity.name.type",
          "support.type"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "name": "Interface",
        "scope": [
          "entity.name.type.interface"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "name": "Property",
        "scope": [
          "variable.other.property",
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "name": "Constant",
        "scope": [
          "variable.other.constant"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "name": "Tag",
        "scope": [
          "entity.name.tag"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "name": "Attribute",
        "scope": [
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "name": "Punctuation",
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "name": "Bracket",
        "scope": [
          "punctuation.definition.block",
          "punctuation.definition.parameters"
        ],
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "name": "Import/Export",
        "scope": [
          "keyword.control.import",
          "keyword.control.export",
          "keyword.control.from"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "name": "Regex",
        "scope": [
          "string.regexp"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "name": "Escape Character",
        "scope": [
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "name": "Markdown Heading",
        "scope": [
          "markup.heading",
          "entity.name.section"
        ],
        "settings": {
          "foreground": "#e06c75",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Bold",
        "scope": [
          "markup.bold"
        ],
        "settings": {
          "foreground": "#d19a66",
          "fontStyle": "bold"
        }
      },
      {
        "name": "Markdown Italic",
        "scope": [
          "markup.italic"
        ],
        "settings": {
          "foreground": "#c678dd",
          "fontStyle": "italic"
        }
      },
      {
        "name": "Markdown Code",
        "scope": [
          "markup.inline.raw",
          "markup.fenced_code"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "name": "Markdown Link",
        "scope": [
          "markup.underline.link"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "name": "JSON Key",
        "scope": [
          "support.type.property-name.json"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      }
    ]
  }
};

export const defaultBootFile: string = "# Welcome to Ultra\n\nA terminal-native code editor built with TypeScript and Bun.\n\n## Quick Start\n\n- **Ctrl+P** - Quick Open (find files)\n- **Ctrl+Shift+P** - Command Palette\n- **Ctrl+`** - Toggle Terminal\n- **Ctrl+B** - Toggle Sidebar\n\n## Getting Help\n\n- Press **Ctrl+Shift+P** and type \"help\" to see available commands\n- Visit https://github.com/zorz/ultra for documentation\n\n## License\n\nUltra is licensed under BSL 1.1. See LICENSE for details.\n";
